// <auto-generated />
using System;
using BookstoreApplication.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BookstoreApplication.Migrations
{
    [DbContext(typeof(BookstoreDbContext))]
    partial class BookstoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BookstoreApplication.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Biography")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Birthday");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Biography = "Nobelovac",
                            DateOfBirth = new DateTime(1892, 10, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Ivo Andrić"
                        },
                        new
                        {
                            Id = 2,
                            Biography = "Enciklopedista",
                            DateOfBirth = new DateTime(1935, 2, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Danilo Kiš"
                        },
                        new
                        {
                            Id = 3,
                            Biography = "Prva akademkinja",
                            DateOfBirth = new DateTime(1877, 2, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Isidora Sekulić"
                        },
                        new
                        {
                            Id = 4,
                            Biography = "Modernista",
                            DateOfBirth = new DateTime(1893, 10, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Miloš Crnjanski"
                        },
                        new
                        {
                            Id = 5,
                            Biography = "Satiričar",
                            DateOfBirth = new DateTime(1864, 10, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Branislav Nušić"
                        });
                });

            modelBuilder.Entity("BookstoreApplication.Models.AuthorAward", b =>
                {
                    b.Property<int>("AuthorId")
                        .HasColumnType("integer");

                    b.Property<int>("AwardId")
                        .HasColumnType("integer");

                    b.Property<int>("YearReceived")
                        .HasColumnType("integer");

                    b.HasKey("AuthorId", "AwardId");

                    b.HasIndex("AwardId");

                    b.ToTable("AuthorAwardBridge", (string)null);

                    b.HasData(
                        new
                        {
                            AuthorId = 1,
                            AwardId = 3,
                            YearReceived = 1961
                        },
                        new
                        {
                            AuthorId = 1,
                            AwardId = 4,
                            YearReceived = 1976
                        },
                        new
                        {
                            AuthorId = 2,
                            AwardId = 1,
                            YearReceived = 1983
                        },
                        new
                        {
                            AuthorId = 2,
                            AwardId = 4,
                            YearReceived = 1985
                        },
                        new
                        {
                            AuthorId = 3,
                            AwardId = 4,
                            YearReceived = 1930
                        },
                        new
                        {
                            AuthorId = 3,
                            AwardId = 2,
                            YearReceived = 1935
                        },
                        new
                        {
                            AuthorId = 4,
                            AwardId = 1,
                            YearReceived = 1929
                        },
                        new
                        {
                            AuthorId = 4,
                            AwardId = 2,
                            YearReceived = 1931
                        },
                        new
                        {
                            AuthorId = 5,
                            AwardId = 2,
                            YearReceived = 1929
                        },
                        new
                        {
                            AuthorId = 5,
                            AwardId = 1,
                            YearReceived = 1930
                        },
                        new
                        {
                            AuthorId = 5,
                            AwardId = 4,
                            YearReceived = 1932
                        },
                        new
                        {
                            AuthorId = 2,
                            AwardId = 3,
                            YearReceived = 1986
                        },
                        new
                        {
                            AuthorId = 4,
                            AwardId = 3,
                            YearReceived = 1933
                        },
                        new
                        {
                            AuthorId = 3,
                            AwardId = 1,
                            YearReceived = 1936
                        },
                        new
                        {
                            AuthorId = 1,
                            AwardId = 1,
                            YearReceived = 1955
                        });
                });

            modelBuilder.Entity("BookstoreApplication.Models.Award", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("YearEstablished")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Awards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Najbolji roman godine",
                            Name = "NIN-ova nagrada",
                            YearEstablished = 1954
                        },
                        new
                        {
                            Id = 2,
                            Description = "Najbolja drama",
                            Name = "Sterijino pozorje",
                            YearEstablished = 1956
                        },
                        new
                        {
                            Id = 3,
                            Description = "Za književnost",
                            Name = "Nobelova nagrada",
                            YearEstablished = 1901
                        },
                        new
                        {
                            Id = 4,
                            Description = "Za pripovetku",
                            Name = "Andrićeva nagrada",
                            YearEstablished = 1975
                        });
                });

            modelBuilder.Entity("BookstoreApplication.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("integer");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PageCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PublishedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PublisherId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("PublisherId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            ISBN = "9780001",
                            PageCount = 320,
                            PublishedDate = new DateTime(1945, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PublisherId = 1,
                            Title = "Na Drini ćuprija"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 1,
                            ISBN = "9780002",
                            PageCount = 210,
                            PublishedDate = new DateTime(1954, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PublisherId = 2,
                            Title = "Prokleta avlija"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 2,
                            ISBN = "9780003",
                            PageCount = 180,
                            PublishedDate = new DateTime(1983, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PublisherId = 1,
                            Title = "Enciklopedija mrtvih"
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 2,
                            ISBN = "9780004",
                            PageCount = 200,
                            PublishedDate = new DateTime(1968, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PublisherId = 3,
                            Title = "Bašta, pepeo"
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 3,
                            ISBN = "9780005",
                            PageCount = 150,
                            PublishedDate = new DateTime(1930, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PublisherId = 2,
                            Title = "Analitički trenuci"
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 3,
                            ISBN = "9780006",
                            PageCount = 120,
                            PublishedDate = new DateTime(1914, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PublisherId = 1,
                            Title = "Pisma iz Norveške"
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 4,
                            ISBN = "9780007",
                            PageCount = 400,
                            PublishedDate = new DateTime(1929, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PublisherId = 3,
                            Title = "Seobe"
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 4,
                            ISBN = "9780008",
                            PageCount = 100,
                            PublishedDate = new DateTime(1919, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PublisherId = 2,
                            Title = "Lirika Itake"
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 5,
                            ISBN = "9780009",
                            PageCount = 130,
                            PublishedDate = new DateTime(1929, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PublisherId = 1,
                            Title = "Gospođa ministarka"
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 5,
                            ISBN = "9780010",
                            PageCount = 140,
                            PublishedDate = new DateTime(1906, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PublisherId = 3,
                            Title = "Narodni poslanik"
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 5,
                            ISBN = "9780011",
                            PageCount = 160,
                            PublishedDate = new DateTime(1924, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PublisherId = 2,
                            Title = "Autobiografija"
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 5,
                            ISBN = "9780012",
                            PageCount = 110,
                            PublishedDate = new DateTime(1936, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PublisherId = 1,
                            Title = "Dr"
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 1,
                            ISBN = "9780013",
                            PageCount = 280,
                            PublishedDate = new DateTime(2017, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PublisherId = 2,
                            Title = "Senke nad Balkanom"
                        },
                        new
                        {
                            Id = 14,
                            AuthorId = 2,
                            ISBN = "9780014",
                            PageCount = 450,
                            PublishedDate = new DateTime(1986, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PublisherId = 3,
                            Title = "Zlatno runo"
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 3,
                            ISBN = "9780015",
                            PageCount = 220,
                            PublishedDate = new DateTime(1962, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PublisherId = 1,
                            Title = "Noć u Lisabonu"
                        },
                        new
                        {
                            Id = 16,
                            AuthorId = 1,
                            ISBN = "9780016",
                            PageCount = 310,
                            PublishedDate = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PublisherId = 3,
                            Title = "Tvrđava"
                        },
                        new
                        {
                            Id = 17,
                            AuthorId = 2,
                            ISBN = "9780017",
                            PageCount = 260,
                            PublishedDate = new DateTime(1953, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PublisherId = 2,
                            Title = "Koreni"
                        },
                        new
                        {
                            Id = 18,
                            AuthorId = 3,
                            ISBN = "9780018",
                            PageCount = 500,
                            PublishedDate = new DateTime(1983, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PublisherId = 1,
                            Title = "Vreme smrti"
                        },
                        new
                        {
                            Id = 19,
                            AuthorId = 4,
                            ISBN = "9780019",
                            PageCount = 340,
                            PublishedDate = new DateTime(1966, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PublisherId = 2,
                            Title = "Derviš i smrt"
                        },
                        new
                        {
                            Id = 20,
                            AuthorId = 5,
                            ISBN = "9780020",
                            PageCount = 180,
                            PublishedDate = new DateTime(1999, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PublisherId = 3,
                            Title = "Čarobna frula"
                        },
                        new
                        {
                            Id = 21,
                            AuthorId = 1,
                            ISBN = "9780021",
                            PageCount = 96,
                            PublishedDate = new DateTime(1943, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PublisherId = 1,
                            Title = "Mali princ"
                        },
                        new
                        {
                            Id = 22,
                            AuthorId = 2,
                            ISBN = "9780022",
                            PageCount = 240,
                            PublishedDate = new DateTime(1976, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PublisherId = 2,
                            Title = "Znakovi pored puta"
                        },
                        new
                        {
                            Id = 23,
                            AuthorId = 3,
                            ISBN = "9780023",
                            PageCount = 360,
                            PublishedDate = new DateTime(1983, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PublisherId = 3,
                            Title = "Besnilo"
                        },
                        new
                        {
                            Id = 24,
                            AuthorId = 4,
                            ISBN = "9780024",
                            PageCount = 290,
                            PublishedDate = new DateTime(2009, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PublisherId = 1,
                            Title = "Konstantinovo raskršće"
                        },
                        new
                        {
                            Id = 25,
                            AuthorId = 5,
                            ISBN = "9780025",
                            PageCount = 270,
                            PublishedDate = new DateTime(1980, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PublisherId = 2,
                            Title = "Knjiga o Milutinu"
                        },
                        new
                        {
                            Id = 26,
                            AuthorId = 1,
                            ISBN = "9780026",
                            PageCount = 230,
                            PublishedDate = new DateTime(1933, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PublisherId = 3,
                            Title = "Legenda o Ali Paši"
                        },
                        new
                        {
                            Id = 27,
                            AuthorId = 2,
                            ISBN = "9780027",
                            PageCount = 190,
                            PublishedDate = new DateTime(2015, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PublisherId = 1,
                            Title = "Velika tajna"
                        },
                        new
                        {
                            Id = 28,
                            AuthorId = 3,
                            ISBN = "9780028",
                            PageCount = 210,
                            PublishedDate = new DateTime(2001, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PublisherId = 2,
                            Title = "Putnik"
                        },
                        new
                        {
                            Id = 29,
                            AuthorId = 4,
                            ISBN = "9780029",
                            PageCount = 170,
                            PublishedDate = new DateTime(1995, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PublisherId = 3,
                            Title = "Zemlja snova"
                        },
                        new
                        {
                            Id = 30,
                            AuthorId = 5,
                            ISBN = "9780030",
                            PageCount = 150,
                            PublishedDate = new DateTime(1988, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PublisherId = 1,
                            Title = "Tišina"
                        },
                        new
                        {
                            Id = 31,
                            AuthorId = 1,
                            ISBN = "9780031",
                            PageCount = 220,
                            PublishedDate = new DateTime(1992, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PublisherId = 2,
                            Title = "Oluja"
                        },
                        new
                        {
                            Id = 32,
                            AuthorId = 2,
                            ISBN = "9780032",
                            PageCount = 260,
                            PublishedDate = new DateTime(2005, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PublisherId = 3,
                            Title = "Zaboravljeni grad"
                        },
                        new
                        {
                            Id = 33,
                            AuthorId = 3,
                            ISBN = "9780033",
                            PageCount = 240,
                            PublishedDate = new DateTime(1998, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PublisherId = 1,
                            Title = "Dolina senki"
                        },
                        new
                        {
                            Id = 34,
                            AuthorId = 4,
                            ISBN = "9780034",
                            PageCount = 180,
                            PublishedDate = new DateTime(2010, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PublisherId = 2,
                            Title = "Pogled u beskraj"
                        },
                        new
                        {
                            Id = 35,
                            AuthorId = 5,
                            ISBN = "9780035",
                            PageCount = 300,
                            PublishedDate = new DateTime(2003, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PublisherId = 3,
                            Title = "Kamen mudrosti"
                        },
                        new
                        {
                            Id = 36,
                            AuthorId = 1,
                            ISBN = "9780036",
                            PageCount = 210,
                            PublishedDate = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PublisherId = 1,
                            Title = "Plavi horizonti"
                        },
                        new
                        {
                            Id = 37,
                            AuthorId = 2,
                            ISBN = "9780037",
                            PageCount = 190,
                            PublishedDate = new DateTime(2007, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PublisherId = 2,
                            Title = "Tajna šifre"
                        },
                        new
                        {
                            Id = 38,
                            AuthorId = 3,
                            ISBN = "9780038",
                            PageCount = 160,
                            PublishedDate = new DateTime(1996, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PublisherId = 3,
                            Title = "Zvezdana prašina"
                        },
                        new
                        {
                            Id = 39,
                            AuthorId = 4,
                            ISBN = "9780039",
                            PageCount = 280,
                            PublishedDate = new DateTime(2012, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PublisherId = 1,
                            Title = "Okean tišine"
                        },
                        new
                        {
                            Id = 40,
                            AuthorId = 5,
                            ISBN = "9780040",
                            PageCount = 250,
                            PublishedDate = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PublisherId = 2,
                            Title = "Grad bez imena"
                        });
                });

            modelBuilder.Entity("BookstoreApplication.Models.Publisher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Publishers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Beograd",
                            Name = "Laguna",
                            Website = "https://laguna.rs"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Novi Sad",
                            Name = "Zavod za udžbenike",
                            Website = "https://zavod.co.rs"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Beograd",
                            Name = "Geopoetika",
                            Website = "https://geopoetika.com"
                        });
                });

            modelBuilder.Entity("BookstoreApplication.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("IdentityRole<Guid>");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2301d884-221a-4e7d-b509-0113dcc043e1"),
                            Name = "Editor",
                            NormalizedName = "EDITOR"
                        },
                        new
                        {
                            Id = new Guid("5b00155d-77a2-438c-b18f-dc1cc8af5a43"),
                            Name = "Librarian",
                            NormalizedName = "LIBRARIAN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BookstoreApplication.Models.AuthorAward", b =>
                {
                    b.HasOne("BookstoreApplication.Models.Author", "Author")
                        .WithMany("AuthorAwards")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookstoreApplication.Models.Award", "Award")
                        .WithMany("AuthorAwards")
                        .HasForeignKey("AwardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Award");
                });

            modelBuilder.Entity("BookstoreApplication.Models.Book", b =>
                {
                    b.HasOne("BookstoreApplication.Models.Author", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookstoreApplication.Models.Publisher", "Publisher")
                        .WithMany()
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("BookstoreApplication.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("BookstoreApplication.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookstoreApplication.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("BookstoreApplication.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BookstoreApplication.Models.Author", b =>
                {
                    b.Navigation("AuthorAwards");
                });

            modelBuilder.Entity("BookstoreApplication.Models.Award", b =>
                {
                    b.Navigation("AuthorAwards");
                });
#pragma warning restore 612, 618
        }
    }
}
